# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "nuget"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    # Check for npm updates on Saturdays
      day: "saturday"
      time: "09:00"
      timezone: "Europe/Berlin"
    # Add reviewers
    reviewers:
      - "VILLAN3LL3"
