# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
  - repository: Frontend
    type: github
    endpoint: Azure Devops OrsoDevOps
    name: orso-co/orso-arpa-web-extended
    ref: main
    trigger:
    - staging

trigger:
- develop
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  - group: arpa-base-urls
  - name: backendWorkingDirectory
    value: '$(AGENT.BUILDDIRECTORY)\Orso.Arpa.Api'
  - name: frontendWorkingDirectory
    value: '$(AGENT.BUILDDIRECTORY)\Orso.Arpa.Web'
  - name: solution
    value: 'Orso.Arpa.Api\**\*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: frontendOutputPath
    value: '..\a\Orso.Arpa.Api\wwwroot'
  - name: stage
    value: 'staging'
  - name: targetFramework
    value: '9.0'

steps:
- checkout: self
  path: 'Orso.Arpa.Api'
- checkout: Frontend
  path: 'Orso.Arpa.Web'
- task: UseDotNet@2
  displayName: Use .NET SDK $(targetFramework).x
  inputs:
    packageType: 'sdk'
    version: '$(targetFramework).x'
- task: DotNetCoreCLI@2
  displayName: Restore Backend
  inputs:
    command: restore
    projects: '$(backendWorkingDirectory)/**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build Backend
  inputs:
    command: build
    projects: '$(backendWorkingDirectory)/**/Orso.Arpa.Api.csproj'
    arguments: --configuration $(BuildConfiguration) --no-restore
- task: DotNetCoreCLI@2
  displayName: Publish Backend
  inputs:
    command: publish
    projects: '$(backendWorkingDirectory)/**/Orso.Arpa.Api.csproj'
    publishWebProjects: false
    arguments: --configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)"
    zipAfterPublish: false
- task: NodeTool@0
  inputs:
    versionSpec: '18.19'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'Install Frontend Dependencies'
  workingDirectory: $(frontendWorkingDirectory)
- script: npx ng build --configuration staging --output-path $(frontendOutputPath)
  displayName: 'Build Frontend'
  workingDirectory: $(frontendWorkingDirectory)
- task: ArchiveFiles@2
  displayName: Create .zip File
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)/Orso.Arpa.Api'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Orso.Arpa.Api.zip'
    replaceExistingArchive: true
    verbose: true
- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)/Orso.Arpa.Api.zip
    ArtifactName: 'orso-arpa-$(stage)'
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
