# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
  - repository: Frontend
    type: github
    endpoint: Azure Devops OrsoDevOps
    name: orso-co/Orso.Arpa.Web.Dev
    ref: develop
    trigger:
    - develop
    
trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  backendWorkingDirectory: '$(AGENT.BUILDDIRECTORY)\Backend'
  frontendWorkingDirectory: '$(AGENT.BUILDDIRECTORY)\Frontend'
  solution: 'Backend\**\*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  BuildParameters.RestoreBuildProjects: '**\*.csproj'
  frontendOutputPath: '..\Backend\bin\$(buildConfiguration)\net5.0\wwwroot'

steps:
- checkout: self
  path: 'Backend'
- checkout: Frontend
  path: 'Frontend'
- task: Bash@3
  displayName: Print variables
  inputs:
    targetType: 'inline'
    script: 'env | sort'
- task: UseDotNet@2
  displayName: User .NET SDK 5.0.x
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
- task: DotNetCoreCLI@2
  displayName: Restore Backend
  inputs:
    command: restore
    projects: $(BuildParameters.RestoreBuildProjects)
- task: DotNetCoreCLI@2
  displayName: Build Backend
  inputs:
    command: 'build'
    projects: $(BuildParameters.RestoreBuildProjects)
    arguments: --configuration $(BuildConfiguration)
    workingDirectory: $(backendWorkingDirectory)
- task: NodeTool@0
  inputs:
    versionSpec: '16.10'
  displayName: 'Install Node.js'
- script: npm install
  displayName: 'Install Frontend Dependencies'
  workingDirectory: $(frontendWorkingDirectory)
- script: npx ng build --configuration dev --output-path $(frontendOutputPath)
  displayName: 'Build'
  workingDirectory: $(frontendWorkingDirectory)
- task: PowerShell@2
  displayName: List Files
  inputs:
    targetType: 'inline'
    script: 'tree /f $(AGENT.BUILDDIRECTORY)'
    failOnStderr: true
    showWarnings: true
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: --configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)"
    zipAfterPublish: true
    workingDirectory: $(backendWorkingDirectory)
- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    ArtifactName: orso-arpa-develop
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
