//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orso.Arpa.Application.Resources.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationValidators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationValidators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orso.Arpa.Application.Resources.Cultures.ApplicationValidators", typeof(ApplicationValidators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        internal static string Password_must_be_at_least_6_characters {
            get {
                return ResourceManager.GetString("Password must be at least 6 characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit.
        /// </summary>
        internal static string Password_must_contain_at_least_one_digit {
            get {
                return ResourceManager.GetString("Password must contain at least one digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter.
        /// </summary>
        internal static string Password_must_contain_at_least_one_lowercase_letter {
            get {
                return ResourceManager.GetString("Password must contain at least one lowercase letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character.
        /// </summary>
        internal static string Password_must_contain_at_least_one_special_character {
            get {
                return ResourceManager.GetString("Password must contain at least one special character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter.
        /// </summary>
        internal static string Password_must_contain_at_least_one_uppercase_letter {
            get {
                return ResourceManager.GetString("Password must contain at least one uppercase letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username may only contain alphanumeric characters.
        /// </summary>
        internal static string Username_may_only_contain_alphanumeric_characters {
            get {
                return ResourceManager.GetString("Username may only contain alphanumeric characters", resourceCulture);
            }
        }
    }
}
