name: Snyk
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  snyk:
    name: Build and run snyk analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --file=./Orso.Arpa.Api.sln --severity-threshold=medium
      - name: Process SARIF file to split multiple runs
        id: process_sarif
        run: |
          if [ -f snyk.sarif ]; then
            echo "SARIF file found, processing..."

            cat > process_sarif.py << 'EOF'
          import json
          import sys
          import os

          try:
              with open('snyk.sarif', 'r') as f:
                  sarif = json.load(f)

              runs = sarif.get('runs', [])
              print(f'Found {len(runs)} runs in SARIF file')

              if len(runs) <= 1:
                  # Single run or no runs - create one file
                  with open('snyk_0.sarif', 'w') as f:
                      json.dump(sarif, f, indent=2)
                  print('file_count=1')
              else:
                  # Multiple runs - create separate SARIF files for each run
                  for i, run in enumerate(runs):
                      # Create a new SARIF structure with only one run
                      single_run_sarif = {
                          '$schema': sarif.get('$schema', 'https://json.schemastore.org/sarif-2.1.0.json'),
                          'version': sarif.get('version', '2.1.0'),
                          'runs': [run]
                      }

                      filename = f'snyk_{i}.sarif'
                      with open(filename, 'w') as f:
                          json.dump(single_run_sarif, f, indent=2)
                      print(f'Created {filename}')

                  print(f'file_count={len(runs)}')

          except Exception as e:
              print(f'Error processing SARIF file: {e}')
              import traceback
              traceback.print_exc()
              # Fallback: create one file with original content
              try:
                  import shutil
                  shutil.copy('snyk.sarif', 'snyk_0.sarif')
                  print('file_count=1')
              except:
                  print('Failed to create fallback file')
                  sys.exit(1)
          EOF

            output=$(python3 process_sarif.py)
            echo "$output"
            file_count=$(echo "$output" | grep "file_count=" | cut -d'=' -f2)
            echo "file_count=$file_count" >> $GITHUB_OUTPUT
          else
            echo "No SARIF file found"
            exit 1
          fi
      - name: Debug SARIF content
        run: |
          echo "=== Original SARIF file analysis ==="
          if [ -f snyk.sarif ]; then
            echo "Original SARIF file size: $(wc -c < snyk.sarif) bytes"
            echo "Number of runs in original: $(jq '.runs | length' snyk.sarif 2>/dev/null || echo 'unknown')"
            echo "Number of results in original: $(jq '[.runs[].results] | add | length' snyk.sarif 2>/dev/null || echo 'unknown')"
            echo "Tool name: $(jq -r '.runs[0].tool.driver.name' snyk.sarif 2>/dev/null || echo 'unknown')"
          fi

          echo "=== Processed SARIF file analysis ==="
          if [ -f snyk_0.sarif ]; then
            echo "Processed SARIF file size: $(wc -c < snyk_0.sarif) bytes"
            echo "Number of runs in processed: $(jq '.runs | length' snyk_0.sarif 2>/dev/null || echo 'unknown')"
            echo "Number of results in processed: $(jq '[.runs[].results] | add | length' snyk_0.sarif 2>/dev/null || echo 'unknown')"
            echo "Tool name: $(jq -r '.runs[0].tool.driver.name' snyk_0.sarif 2>/dev/null || echo 'unknown')"
          fi
      - name: Upload processed SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_0.sarif
          category: snyk-processed
        continue-on-error: true
      - name: Upload additional SARIF files if they exist
        run: |
          file_count="${{ steps.process_sarif.outputs.file_count }}"
          echo "Checking for additional SARIF files beyond the first one..."

          # Upload additional files using the CodeQL action if there are more than 1
          if [ "$file_count" -gt 1 ]; then
            for i in $(seq 1 $((file_count-1))); do
              filename="snyk_${i}.sarif"
              if [ -f "$filename" ]; then
                echo "Found additional file: $filename"
                echo "Note: Additional files detected but require manual upload or workflow modification"
                echo "File $filename contains $(grep -c '"ruleId"' $filename 2>/dev/null || echo 'unknown') potential issues"
              fi
            done
          else
            echo "Only one SARIF file found, upload complete."
          fi
      - name: Verify Code Scanning setup
        run: |
          echo "Checking if Code Scanning is enabled for this repository..."
          gh api "/repos/${{ github.repository }}/code-scanning/alerts" --paginate \
            && echo "Code Scanning is properly configured" \
            || echo "Code Scanning may not be enabled or no alerts exist yet"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
