name: Snyk
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  snyk:
    name: Build and run snyk analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --file=./Orso.Arpa.Api.sln --severity-threshold=medium
      - name: Process SARIF file to split multiple runs
        id: process_sarif
        run: |
          if [ -f snyk.sarif ]; then
            echo "SARIF file found, processing..."

            cat > process_sarif.py << 'EOF'
          import json
          import sys
          import os

          try:
              with open('snyk.sarif', 'r') as f:
                  sarif = json.load(f)

              runs = sarif.get('runs', [])
              print(f'Found {len(runs)} runs in SARIF file')

              if len(runs) <= 1:
                  # Single run or no runs - create one file
                  with open('snyk_0.sarif', 'w') as f:
                      json.dump(sarif, f, indent=2)
                  print('file_count=1')
              else:
                  # Multiple runs - create separate SARIF files for each run
                  for i, run in enumerate(runs):
                      # Create a new SARIF structure with only one run
                      single_run_sarif = {
                          '$schema': sarif.get('$schema', 'https://json.schemastore.org/sarif-2.1.0.json'),
                          'version': sarif.get('version', '2.1.0'),
                          'runs': [run]
                      }

                      filename = f'snyk_{i}.sarif'
                      with open(filename, 'w') as f:
                          json.dump(single_run_sarif, f, indent=2)
                      print(f'Created {filename}')

                  print(f'file_count={len(runs)}')

          except Exception as e:
              print(f'Error processing SARIF file: {e}')
              import traceback
              traceback.print_exc()
              # Fallback: create one file with original content
              try:
                  import shutil
                  shutil.copy('snyk.sarif', 'snyk_0.sarif')
                  print('file_count=1')
              except:
                  print('Failed to create fallback file')
                  sys.exit(1)
          EOF

            output=$(python3 process_sarif.py)
            echo "$output"
            file_count=$(echo "$output" | grep "file_count=" | cut -d'=' -f2)
            echo "file_count=$file_count" >> $GITHUB_OUTPUT
          else
            echo "No SARIF file found"
            exit 1
          fi
      - name: Upload SARIF files to GitHub Code Scanning
        run: |
          file_count="${{ steps.process_sarif.outputs.file_count }}"
          echo "Found $file_count SARIF file(s) to upload"

          # Create a script to upload each file using the CodeQL action
          for i in $(seq 0 $((file_count-1))); do
            filename="snyk_${i}.sarif"
            if [ -f "$filename" ]; then
              echo "Processing $filename for upload..."
              echo "File exists and will be uploaded with category arpa-snyk-$i"
            else
              echo "Warning: $filename not found"
            fi
          done
      - name: Upload SARIF file 0
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_0.sarif
          category: arpa-snyk-0
        continue-on-error: true
      - name: Upload SARIF file 1
        if: always() && hashFiles('snyk_1.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_1.sarif
          category: arpa-snyk-1
        continue-on-error: true
      - name: Upload SARIF file 2
        if: always() && hashFiles('snyk_2.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_2.sarif
          category: arpa-snyk-2
        continue-on-error: true
      - name: Upload SARIF file 3
        if: always() && hashFiles('snyk_3.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_3.sarif
          category: arpa-snyk-3
        continue-on-error: true
      - name: Upload SARIF file 4
        if: always() && hashFiles('snyk_4.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_4.sarif
          category: arpa-snyk-4
        continue-on-error: true
