name: Snyk
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  snyk:
    name: Build and run snyk analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --file=./Orso.Arpa.Api.sln --severity-threshold=medium
      - name: Process SARIF file to ensure unique categories
        run: |
          if [ -f snyk.sarif ]; then
            echo "SARIF file found, processing..."

            cat > process_sarif.py << 'EOF'
          import json
          import sys
          import shutil

          try:
              with open('snyk.sarif', 'r') as f:
                  sarif = json.load(f)

              print(f'Found {len(sarif.get("runs", []))} runs in SARIF file')

              # If there are multiple runs, we need to create separate SARIF files
              # or modify the category at the tool level, not properties level
              runs = sarif.get('runs', [])

              if len(runs) <= 1:
                  # Single run or no runs - just copy the file
                  shutil.copy('snyk.sarif', 'snyk_processed.sarif')
                  print('Single run detected, using original file')
              else:
                  # Multiple runs - create a single SARIF with unique categories
                  for i, run in enumerate(runs):
                      # Set category in the tool's properties, not run properties
                      if 'tool' in run and 'driver' in run['tool']:
                          if 'properties' not in run['tool']['driver']:
                              run['tool']['driver']['properties'] = {}
                          run['tool']['driver']['properties']['category'] = f'arpa-snyk-{i}'

                      # Also set in run properties as backup
                      if 'properties' not in run:
                          run['properties'] = {}
                      run['properties']['category'] = f'arpa-snyk-{i}'

                  with open('snyk_processed.sarif', 'w') as f:
                      json.dump(sarif, f, indent=2)

                  print(f'Processed {len(runs)} runs with unique categories')

          except Exception as e:
              print(f'Error processing SARIF file: {e}')
              import traceback
              traceback.print_exc()
              try:
                  shutil.copy('snyk.sarif', 'snyk_processed.sarif')
                  print('Using original SARIF file due to processing error')
              except:
                  print('Failed to copy original file')
                  sys.exit(1)
          EOF

            python3 process_sarif.py
          else
            echo "No SARIF file found"
            exit 1
          fi
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_processed.sarif
